apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pod-anti-affinity
  name: pod-anti-affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod-anti-affinity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod-anti-affinity
    spec:
      affinity:
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In 
                values:
                - pod-anti-affinity
            topologyKey: kubernetes.io/hostname
      containers:
      - image: bitnami/nginx
        name: nginx
        resources: {}
status: {}
