kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-policy
spec:
  podSelector: 
    matchLabels:
      app: server
  ingress:
  - from:
    - podSelector: 
        matchLabels:
          allow: "true"
