kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: select
  namespace: target
spec:
  podSelector:
    matchLabels:
      host: "server"
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            deployment: clients
        podSelector:
          matchLabels:
            access: "allow"
      ports:
      - port: 8080
        protocol: TCP
