kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ipblock-lab
  namespace: target
spec:
  podSelector:
    matchLabels:
      host: "server"
  ingress:
    - from:
      ipBlock: "192.168.130.1/24"
