kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-manual
  labels:
    type: volume
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-manual-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
   name: pv-pod
spec:
  volumes:
    - name: pv-manual-storage
      persistentVolumeClaim:
        claimName: pv-manual-claim
  containers:
    - name: pv-container
      image: nginx
      securityContext: 
        privileged: yes
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-manual-storage
