apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"loadtest:v1.0"},"fieldPath":"spec.template.spec.containers[?(@.name==\"loadtest\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2021-12-21T03:02:57Z"
  generation: 6
  labels:
    app: loadtest
    app.kubernetes.io/component: loadtest
    app.kubernetes.io/instance: loadtest
  name: loadtest
  namespace: schedule-review
  resourceVersion: "584252"
  uid: b305b7dc-6632-468e-8630-60f8936429d0
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: loadtest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: loadtest
    spec:
      containers:
      - image: quay.io/redhattraining/loadtest@sha256:14038e28490705cd0e89a0d67b85a260aea332d281977a8930d5a67f24b6fd34
        imagePullPolicy: IfNotPresent
        name: loadtest
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        tier: silver
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-12-21T03:09:24Z"
    lastUpdateTime: "2021-12-21T03:09:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-21T03:02:57Z"
    lastUpdateTime: "2021-12-21T03:13:52Z"
    message: ReplicaSet "loadtest-749cc9bdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
