apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "local-storage" 
spec:
  storageClassDevices:
    - storageClassName: "localblock-sc"
#      volumeMode: Block  
      devicePaths: 
        - /dev/loop0
