apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: busybox
    name: busybox
    resources: {}
    envFrom: 
      - configMapRef:
          name: secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
